### ISSUE TITLE
Compiler code uses a non-existing module

### ISSUE THREAD

**Issue by Ponali** [elikaski/BF-it#76]
edited one of the example codes and ran it and the compiler immidiately outputted a "module not found" error. i tried installing it with pip and it didn't help.
```
D:\BF-it>python BF-it.py examples/games/snake.code
Traceback (most recent call last):
  File "D:\BF-it\BF-it.py", line 6, in <module>
    from Compiler import Compiler
  File "D:\BF-it\Compiler\Compiler.py", line 2, in <module>
    from Exceptions import BFSyntaxError, BFSemanticError
ModuleNotFoundError: No module named 'Exceptions'

D:\BF-it>pip install Exceptions
ERROR: Could not find a version that satisfies the requirement Exceptions (from versions: none)
ERROR: No matching distribution found for Exceptions

D:\BF-it>
```

**Comment by elikaski** [comment]
There was an import problem, I fixed it. Thank you for pointing this out :)
